apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml

configMapGenerator:
  - name: tinode-config
    files:
      - config=config.json
    namespace: watchbeats