apiVersion: v1
kind: Service
metadata:
  name: tinode
  labels:
    app.kubernetes.io/name: tinode
    app.kubernetes.io/instance: tinode
  namespace: watchbeats
spec:
  type: ClusterIP
  ports:
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: http
    - port: 16060
      targetPort: 16060
      protocol: TCP
      name: grpc-api
  selector:
    app.kubernetes.io/name: tinode
    app.kubernetes.io/instance: tinode
